### ISSUE TITLE
Various broken links

### ISSUE THREAD

**Issue by kscarlett** [evilsocket/www.pwnagotchi.ai#2]
While working on #1 I found some links I couldn't find the new version for. These are:

### /docs
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/usage.md#training-the-ai
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/configure.md#configuration
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/usage.md#bettercaps-web-ui
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/install.md#flashing-an-image
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/plugins.md
- https://github.com/evilsocket/pwnagotchi/blob/master/docs/hacks.md (I guess this one should go to the hacks section on the docs site directly)

**Comment by leon-th** [comment]
Hi, i corrected in my plugin these links. Could you please look if mine are correct.
Leon T
