### ISSUE TITLE
Add network config section for internet acces of pwnagotchi

### ISSUE THREAD

**Issue by acbekoac** [evilsocket/www.pwnagotchi.ai#30]
on Linux host

sudo sysctl net.ipv4.ip_forward=1
sudo iptables -P FORWARD ACCEPT
sudo iptables -A POSTROUTING -t nat -o usb0 -j MASQUERADE -s 10.0.0.0/24
sudo iptables -t nat -nvL POSTROUTING

**Comment by evilsocket** [comment]
that's the linux_connection_sharing script
