### ISSUE TITLE
Site accessible with & w/o www. prefix causing issues with CORS

### ISSUE THREAD

**Issue by deveth0** [evilsocket/www.pwnagotchi.ai#56]
== Describe the bug
Currently pwnagotchi.ai is accessible both with and w/o www. This causes some issues with CORS as the same origin does not work when using www.pwnagotchi.ai

== To Reproduce

* open https://www.pwnagotchi.ai/map/ => see CORS errors in console, no map
* open https://pwnagotchi.ai/map/ => profit

== Expected behavior
I'd expect to only have one version of the page (most likely without www). This would also prevent any search engine penalties due to duplicate content.

**Comment by evilsocket** [comment]
oh i totally missed this, thanks a ton! solved with a 301 from www to the naked domani 👍
