### ISSUE TITLE
Clear legal section/warning

### ISSUE THREAD

**Issue by ThatLurker** [evilsocket/www.pwnagotchi.ai#83]
Readme should have a clear legal section about the possible illegality of dehauth/WiFi attacks.

**Comment by arch-user-france1** [comment]
yes... It's right....

You can too steel datas from google with intext:"..." etc...    If you don't do any social engineering attack, this would be legal...

It's the same like pwnagotchi
I think, we can close this issue...................

BUT:     IT ISN'T LEGAL TO DEAUTHENTICATE STATIONS, THATS NOT LEGAL, SO YOU HAVE TO EDIT YOUR CONFIG.TOML OR CONFIG.YML FILE!!!!!

**Comment by arch-user-france1** [comment]
You can use the default.toml file and show on very long down- until last line and add the config with dontknowwhat.deauthenticateordomething and set to false

**Comment by arch-user-france1** [comment]
Config is in /etc/pwnagotchi
